colour:
  neutral:
    base: 
      rgb: '0,62,82'
    
    one:
      darkest:
        value: 'rgba({colour.neutral.base.rgb}, {colour.neutral.one.darkest.alpha})'
        alpha: '0.9'
      
      dark:
        value: 'rgba({colour.neutral.base.rgb}, {colour.neutral.one.dark.alpha})'
        alpha: '0.6'
      
      lighter:
        value: 'rgba({colour.neutral.base.rgb}, {colour.neutral.one.lighter.alpha})'
        alpha: '0.3'
      
      lightest:
        value: 'rgba({colour.neutral.base.rgb}, {colour.neutral.one.lightest.alpha})'
        alpha: '0.15'
    
    two:
      light: '#e6ecee'
      lighter: '#f2f5f6'
      lightest: '#f7f5f9'
  
  gray:
    darkest: '#4f5053'
    lighter: '#858989'
  
  primary:
    darkest:
      value: '#00498f'
    dark:
      value: '#0092c8'
    
    light:
      rgb: '43,176,212'
      value: rgb({colour.primary.light.rgb})
    
    lighter:
      value: 'rgba({colour.primary.light.rgb}, {colour.primary.lighter.alpha})'
      alpha: '0.5'
    
    lightest:
      value: 'rgba({colour.primary.light.rgb}, {colour.primary.lightest.alpha})'
      alpha: '0.15'

  success:
    dark: '#00b284'
    lighter: '#80d0bb'
    lightest: '#e5f5f1'
  
  error:
    darkest: '#da4465'
    dark: '#de607c'
    lightest: '#fbecef'