color:
  neutral:
    base: 
      rgb: '0,62,82'
    
    one:
      darkest:
        value: 'rgba({color.neutral.base.rgb}, {color.neutral.one.darkest.alpha})'
        alpha: '0.9'
      
      dark:
        value: 'rgba({color.neutral.base.rgb}, {color.neutral.one.dark.alpha})'
        alpha: '0.6'
      
      lighter:
        value: 'rgba({color.neutral.base.rgb}, {color.neutral.one.lighter.alpha})'
        alpha: '0.3'
      
      lightest:
        value: 'rgba({color.neutral.base.rgb}, {color.neutral.one.lightest.alpha})'
        alpha: '0.15'
    
    two:
      light: 
        value: '#e6ecee'
      lighter: 
        value: '#f2f5f6'
      lightest: 
        value: '#f7f5f9'
  
  gray:
    darkest: 
      value: '#4f5053'
    lighter: 
      value: '#858989'
  
  primary:
    darkest:
      value: '#00498f'
    dark:
      value: '#0092c8'
    
    light:
      rgb: '43,176,212'
      value: rgb({color.primary.light.rgb})
    
    lighter:
      value: 'rgba({color.primary.light.rgb}, {color.primary.lighter.alpha})'
      alpha: '0.5'
    
    lightest:
      value: 'rgba({color.primary.light.rgb}, {color.primary.lightest.alpha})'
      alpha: '0.15'

  success:
    dark: 
      value: '#00b284'
    lighter: 
      value: '#80d0bb'
    lightest: 
      value: '#e5f5f1'
  
  error:
    darkest: 
      value: '#da4465'
    dark: 
      value: '#de607c'
    lightest: 
      value: '#fbecef'
  
  metro:
    darkest:
      rgb: '15,136,141'
      value: 'rgb({color.metro.darkest.rgb})'
    
    dark:
      rgb: '23,197,203'
      value: 'rgb({color.metro.dark.rgb})'
    
    light: 
      value: '#8BE2E5'
    
    lighter:
      value: 'rgba({color.metro.darkest.rgb}, {color.metro.lighter.alpha})'
      alpha: '0.2'
    
    lightest:
      value: 'rgba({color.metro.dark.rgb}, {color.metro.lightest.alpha})'
      alpha: '0.2'
  
  regional:
    darkest:
      rgb: '43,111,156'
      value: 'rgb({color.regional.darkest.rgb})'
    
    dark:
      rgb: '62,157,221'
      value: 'rgb({color.regional.dark.rgb})'
    
    light: 
      value: '#8BE2E5'
    
    lighter:
      value: 'rgba({color.regional.darkest.rgb}, {color.regional.lighter.alpha})'
      alpha: '0.2'
    
    lightest:
      value: 'rgba({color.regional.dark.rgb}, {color.regional.lightest.alpha})'
      alpha: '0.2'

  global:
    darkest:
      rgb: '82,82,139'
      value: 'rgb({color.global.darkest.rgb})'
    
    dark:
      rgb: '120,119,201'
      value: 'rgb({color.global.dark.rgb})'
    
    light: 
      value: '#8BE2E5'
    
    lighter:
      value: 'rgba({color.global.darkest.rgb}, {color.global.lighter.alpha})'
      alpha: '0.2'
    
    lightest:
      value: 'rgba({color.global.dark.rgb}, {color.global.lightest.alpha})'
      alpha: '0.2'
