colour:
  neutral:
    base: 
      rgb: '0,62,82'
    
    one:
      darkest:
        value: 'rgba({colour.neutral.base.rgb}, {colour.neutral.one.darkest.alpha})'
        alpha: '0.9'
      
      dark:
        value: 'rgba({colour.neutral.base.rgb}, {colour.neutral.one.dark.alpha})'
        alpha: '0.6'
      
      lighter:
        value: 'rgba({colour.neutral.base.rgb}, {colour.neutral.one.lighter.alpha})'
        alpha: '0.3'
      
      lightest:
        value: 'rgba({colour.neutral.base.rgb}, {colour.neutral.one.lightest.alpha})'
        alpha: '0.15'
    
    two:
      light: 
        value: '#e6ecee'
      lighter: 
        value: '#f2f5f6'
      lightest: 
        value: '#f7f5f9'
  
  gray:
    darkest: 
      value: '#4f5053'
    lighter: 
      value: '#858989'
  
  primary:
    darkest:
      value: '#00498f'
    dark:
      value: '#0092c8'
    
    light:
      rgb: '43,176,212'
      value: rgb({colour.primary.light.rgb})
    
    lighter:
      value: 'rgba({colour.primary.light.rgb}, {colour.primary.lighter.alpha})'
      alpha: '0.5'
    
    lightest:
      value: 'rgba({colour.primary.light.rgb}, {colour.primary.lightest.alpha})'
      alpha: '0.15'

  success:
    dark: 
      value: '#00b284'
    lighter: 
      value: '#80d0bb'
    lightest: 
      value: '#e5f5f1'
  
  error:
<<<<<<< HEAD
    darkest: 
      value: '#da4465'
    dark: 
      value: '#de607c'
    lightest: 
      value: '#fbecef'
=======
    darkest: '#da4465'
    dark: '#de607c'
    lightest: '#fbecef'
  
  metro:
    darkest:
      rgb: '15,136,141'
      value: 'rgb({colour.metro.darkest.rgb})'
    
    dark:
      rgb: '23,197,203'
      value: 'rgb({colour.metro.dark.rgb})'
    
    light: '#8BE2E5'
    
    lighter:
      value: 'rgba({colour.metro.darkest.rgb}, {colour.metro.lighter.alpha})'
      alpha: '0.2'
    
    lightest:
      value: 'rgba({colour.metro.dark.rgb}, {colour.metro.lightest.alpha})'
      alpha: '0.2'
  
  regional:
    darkest:
      rgb: '43,111,156'
      value: 'rgb({colour.regional.darkest.rgb})'
    
    dark:
      rgb: '62,157,221'
      value: 'rgb({colour.regional.dark.rgb})'
    
    light: '#8BE2E5'
    
    lighter:
      value: 'rgba({colour.regional.darkest.rgb}, {colour.regional.lighter.alpha})'
      alpha: '0.2'
    
    lightest:
      value: 'rgba({colour.regional.dark.rgb}, {colour.regional.lightest.alpha})'
      alpha: '0.2'

  global:
    darkest:
      rgb: '82,82,139'
      value: 'rgb({colour.global.darkest.rgb})'
    
    dark:
      rgb: '120,119,201'
      value: 'rgb({colour.global.dark.rgb})'
    
    light: '#8BE2E5'
    
    lighter:
      value: 'rgba({colour.global.darkest.rgb}, {colour.global.lighter.alpha})'
      alpha: '0.2'
    
    lightest:
      value: 'rgba({colour.global.dark.rgb}, {colour.global.lightest.alpha})'
      alpha: '0.2'
>>>>>>> move chart colour options to color base definition
