color:
  bg:
    metro:
      allocation:
        value: '{color.metro.light.value}'
      
      tx:
        current:
          value: '{color.metro.darkest.value}'
        
        historical:
          value: '{color.metro.lighter.value}'
        
        historicalAvg:
          value: '{color.metro.darkest.value}'
    
      rx:
        current:
          value: '{color.metro.dark.value}'
        
        historical:
          value: '{color.metro.lightest.value}'
        historicalAvg:
          value: '{color.metro.dark.value}'
    
    regional:
      allocation:
        value: '{color.regional.light.value}'
      
      tx:
        current:
          value: '{color.regional.darkest.value}'
        
        historical:
          value: '{color.regional.lighter.value}'
        
        historicalAvg:
          value: '{color.regional.darkest.value}'
    
      rx:
        current:
          value: '{color.regional.dark.value}'
        
        historical:
          value: '{color.regional.lightest.value}'
        
        historicalAvg:
          value: '{color.regional.dark.value}'

    global:
      allocation:
        value: '{color.global.light.value}'
      
      tx:
        current:
          value: '{color.global.darkest.value}'
        
        historical:
          value: '{color.global.lighter.value}'
        
        historicalAvg:
          value: '{color.global.darkest.value}'
    
      rx:
        current:
          value: '{color.global.dark.value}'
        
        historical:
          value: '{color.global.lightest.value}'
        
        historicalAvg:
          value: '{color.global.dark.value}'